[context.production.environment]
  HUGO_VERSION = "0.49.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.49.2"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[[redirects]]
  from = "/feed"
  to = "/feed.xml"
